name: Build and test website
on: push

jobs:
  test_docs:
    name: Test documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download and install mdBook 
        run: curl -L -o mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz && tar -C $HOME/.cargo/bin/ -zvxf mdbook.tar.gz
        env:
          MDBOOK_VERSION: 0.3.1
      - run: mdbook build
      - run: mdbook test

  deploy:
    name: Deploy documentation
    if: github.ref == 'refs/heads/src'
    needs: test_docs
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
      - uses: JamesIves/github-pages-deploy-action@4.0.0
          with:
            branch: master # The branch the action should deploy to.
            folder: book # The folder the action should deploy.